[package]
name = "rustmas-webapi"
version = "0.1.0"
edition = "2021"

[dependencies]
rustmas-animator = { path = "../animator" }

actix-web = "4"
actix-files = "0.6.2"
dotenvy = "0.15.6"
serde = { version = "1.0", features = ["derive"] }

log = "0.4.17"
simplelog = "0.12.0"
