mod animation;
mod barber_pole;
mod blank;
mod brightness_controlled;
mod check;
mod detection_status;
mod direction_controlled;
mod indexing;
mod manual_sweep;
mod rainbow_cable;
mod rainbow_cylinder;
mod rainbow_sphere;
mod rainbow_spiral;
mod rainbow_waterfall;
mod random_sweep;
mod rgb;
mod speed_controlled;
mod sweep;
mod utils;

pub use animation::make_animation;
pub use animation::Animation;
pub use animation::AnimationParameters;
